[package]
name = "rl_ball_sym"
version = "0.1.0"
authors = ["VirxEC"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
json = "0.12.*"

[dependencies]
byteorder = "1.*"

[profile.dev]
opt-level=3
