[package]
name = "rl_ball_sym"
version = "3.1.3"
authors = ["VirxEC"]
edition = "2021"
description = "Rust implementation of ball path prediction for Rocket League; Inspired by Samuel (Chip) P. Mish's C++ utils called RLUtilities"
readme = "README.md"
repository = "https://github.com/VirxEC/rl_ball_sym"
license = "GPL-3.0"
keywords = ["rocket-league", "rlbot", "physics", "simulation"]
categories = ["science", "simulation", "mathematics"]
include = ["src/", "assets/"]
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8"
once_cell = "1.17.1"
criterion = { version = "0.5.0", features = ["html_reports"] }

[dependencies]
byteorder = "1"
glam = "0.24.0"
radsort = "0.1"
combo_vec = "0.5"
include-flate = { version = "0.2.0", optional = true }

[features]
default = ["uncompressed", "standard", "hoops", "dropshot", "throwback"]
uncompressed = []
compression = ["include-flate"]
stable-compression = ["compression", "include-flate/stable"]
fast-math = ["glam/fast-math"]
standard = []
hoops = []
dropshot = []
throwback = []

[package.metadata.docs.rs]
all-features = true

[profile.bench]
codegen-units = 1
lto = true

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
harness = false
