[package]
name = "rl_ball_sym"
version = "2.1.1"
authors = ["VirxEC"]
edition = "2021"
description = "Rust implementation of ball path prediction for Rocket League; Inspired by Samuel (Chip) P. Mish's C++ utils called RLUtilities"
readme = "README.md"
repository = "https://github.com/VirxEC/rl_ball_sym"
license = "GPL-3.0-only"
keywords = ["rocket-league", "rlbot", "physics", "simulation"]
categories = ["science", "simulation", "mathematics"]
include = ["src/", "assets/", "benches/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8"
criterion = { version = "0.3", features = ["html_reports"] }

[dependencies]
byteorder = "1"
glam = "0.21.2"
radsort = "0.1.0"

[features]
fast-math = ["glam/fast-math"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[profile.bench]
codegen-units = 1
lto = "fat"

[[bench]]
name = "benchmarks"
harness = false
