[package]
name = "rl_ball_sym"
version = "4.0.0"
authors = ["VirxEC"]
edition = "2021"
description = "rl_ball_sym is a Rust implementation of ball path prediction for Rocket League; Based on Samuel (Chip) P. Mish's C++ utils called RLUtilities and RocketSim by Zealan"
readme = "README.md"
repository = "https://github.com/VirxEC/rl_ball_sym"
license = "GPL-3.0"
keywords = ["rocket-league", "rlbot", "physics", "simulation"]
categories = ["science", "simulation", "mathematics"]
include = ["src/", "assets/"]
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8"
once_cell = "1.17.1"
criterion = { version = "0.5.0", features = ["html_reports"] }
serde_json = "1.0.107"

[dependencies]
byteorder = "1"
glam = "0.24.0"
radsort = "0.1"
combo_vec = "0.5"
include-flate = { version = "0.3.0", optional = true }
serde = { version = "1.0.188", features = ["derive"], optional = true }

[features]
default = ["uncompressed", "standard", "hoops", "dropshot", "throwback"]
uncompressed = []
compression = ["include-flate"]
standard = []
hoops = []
dropshot = []
throwback = []
serde = ["dep:serde", "glam/serde"]

[profile.release-with-debug]
inherits = "release"
debug = true

[package.metadata.docs.rs]
all-features = true

[profile.bench]
codegen-units = 1
lto = true

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
harness = false

[[example]]
name = "accuracy"
required-features = ["serde"]
